### ISSUE TITLE
Escaped password error

### ISSUE THREAD

**Issue by dwightjack** [Atinux/node-ftps#18]
Hi,

I'm trying to use this module to connect to a FTP server via lftp.
Unfortunately, my password has a `$` sign which gets escaped by `escapeshell` resulting in a login failure.

I've not admin rights to change the password, so i'm guessing if it's safe to remove the escaping or maybe I could change the regexp to be more accurate.

Thanks!

**Comment by Atinux** [comment]
Hi @dwightjack,

Thanks for you feedback.
I updated the module to the version 0.3.2 and there's an escape option now.
So you can do:
``` js
var FTPS = require('ftps');
var ftps = new FTPS({
  host: 'domain.com',
  username: 'Test',
  password: 'yourpasswordwitha$',
  escape: false,
});
```

But the others options will not be escaped:
`ftps.cd('my folder')` will not work.
You will need to do:
`ftps.cd(ftps.escapeshell('my folder'))`

Or you can set ftps.options.escape = true after the initialisation to only have the escape disabled for the username and password!

Cheers!

**Comment by dwightjack** [comment]
Thanks for the prompt reply!

Cheers!
