### ISSUE TITLE
Loop through available files

### ISSUE THREAD

**Issue by sonukapoor** [Atinux/node-ftps#31]
How do I loop through the available files on the server?
 I ran the following command:

ftps.ls();
ftps.exec(function (err, res) {
        console.log(JSON.stringify(res));
});

And the output is:

{"error":null,"data":"drw-rw-rw-  /                   0 2016-06-01 10:14:38 .\n-rw-rw-rw-  /            17919880 2016-05-31 15:03:10 somefile_20160531030158.csv\n-rw-rw-rw-  /            17929819 2016-06-01 10:24:21 someOtherFile_20160601102307.csv\n"}

Can this be converted into a json array or something?

Thanks,

**Comment by Atinux** [comment]
Hi @sonukapoor 

Great question, you can take the data and split it by line:
```js
ftps.ls();
ftps.exec(function (err, res) {
  if (err || res.error) return console.log('An error occured', (err || res.error));
  var lines = res.data.split('\n');
  lines.forEach(function (line) {
    // To parse the line, I recommend the code from node-ftp
    // https://github.com/mscdex/node-ftp/blob/master/lib/parser.js#L77
  });
});
```

I hope it can help you!
