### ISSUE TITLE
Can you show how to access the return values?

### ISSUE THREAD

**Issue by HoosierMike** [Atinux/node-ftps#34]
I cannot tell if it's working or not, I'm not getting any errors, but cannot figure out what is in the responses, they look the same in all calls?

cmds->[0] = "ls"
cmds->_proto = {Array}
cmds->length = 1

is my response in Array? Sorry, not getting it?  I can even give it a bad IP address, no error, no nothing?

**Comment by Atinux** [comment]
Hi @HoosierMike 

Can you give me an example of your code please?
