### ISSUE TITLE
anonymous ftp

### ISSUE THREAD

**Issue by jeromew** [Atinux/node-ftps#36]
Hello,

I am trying to access a FTP server that is anonymous (no username, no password).
 - when I send nothing, `ftps` requires a username
 - when a use a username + password, or usernam + requiresPassword: false, `ftps` does not manage to connect to the remote server

The only way I could get through is by modifying the code to remove the `-u` option.

I could send a PR but it is not clear to me how you want to handle this because of the `requiresPassword` option. I could add a `requiresUsername` option that would remove the check for the option + remove the `-u user,pass` option.

tell me what you think

**Comment by Atinux** [comment]
What if the username is optional and we add the -u option if defined?

I would love you to do a PR for this :)

**Comment by jeromew** [comment]
ok will do that

**Comment by jeromew** [comment]
linked to PR #37

**Comment by Atinux** [comment]
It's now possible in the version 0.5.0 :)
