### ISSUE TITLE
Can this module upload a buffer to an FTP server without first writing it to disk?

### ISSUE THREAD

**Issue by jazoom** [Atinux/node-ftps#41]

**Comment by Atinux** [comment]
Sorry @jazoom it's not possible since `node-ftps` spawn the `lftp` command under the hood.

You can still write the file in the tmp folder (use [os.tmpdir()](https://nodejs.org/api/os.html#os_os_tmpdir) from node.js)

**Comment by jazoom** [comment]
Thank you
