### ISSUE TITLE
are unable to find another cygwin DLL

### ISSUE THREAD

**Issue by chqfly** [Atinux/node-ftps#42]
my code:

var ftps = new FTPS({
        host: '********',
        username: '***',
        password: '***',
        protocol: 'sftp', // Optional, values : 'ftp', 'sftp', 'ftps', ... default: 'ftp'
        port: 22,
        escape: true,
        retries: 2, // Optional, defaults to 1 (1 = no retries, 0 = unlimited retries)
        timeout: 10,
        retryInterval: 5,
        retryMultiplier: 1,
        requiresPassword: true,
        autoConfirm: true,
        cwd: '',
        additionalLftpCommands: ''
    });

    ftps.cd('/var/www/html/test/').addFile('dist/html/index.html').exec(function(err,res) {
        console.log(res);
    });

get message: 
{ error: 'cd: Fatal error: max-retries exceeded (are unable to find another cygwin DLL.)\nput: dist/html/index.html: Fatal error: max-retries exceeded (are unable to find another cygwin DLL.)\n',

please help me! thank you!

**Comment by Atinux** [comment]
Are you sure that `/var/www/html/test/` exists?

See https://app.assembla.com/spaces/AssemblaSupport/tickets/9104/details?comment=407662323
