### ISSUE TITLE
ERROR-fixed it.

### ISSUE THREAD

**Issue by jorry** [Atinux/node-ftps#46]
Error on adding file: ls: Fatal error: max-retries exceeded
rm: Fatal error: max-retries exceeded
cd: Fatal error: max-retries exceeded
put: /Users/iqianjin-liujiawei/work/tinker/tinker-shadow-manager/public/uploads/ljw.png: Fatal error: max-retries exceeded

How to fix it ?

my code:

ftps.ls().rm('iqianjin_V5.0.0.apk').cd(ftpUtils.apkDir).addFile('/Users/iqianjin-liujiawei/work/tinker/tinker-shadow-manager/public/uploads/ljw.png').exec(function (err, res){
        if (err || res.error)
            return console.log('Error on adding file:', (err || res.error));
        console.log('File added on server!');
    });

**Comment by Atinux** [comment]
It seems that you credentials are invalid @jorry
