### ISSUE TITLE
Is it possible to put piped stream data?

### ISSUE THREAD

**Issue by dustinbolton** [Atinux/node-ftps#48]
I'd like to upload via a stream by piping in data.  Essentially I'm wanting to pipe streamed data from one server via get() to another server via put().  Is this possible with this library any way?

**Comment by Atinux** [comment]
Hi @dustinbolton 

Sorry we can't since we depend on `lftp` binary.

**Comment by dustinbolton** [comment]
@Atinux I did some more research and I may have found a way that this would be possible. I'm not quite I'm understanding exactly how to make this work with node-ftps, but I have an example of how I'm thinking it might work below.

I discovered lftp can accept piped in input via stdin (source: https://github.com/lavv17/lftp/issues/104 ):
```
put /dev/stdin -o remote_file
```
The child_process and duplex-child-process (which uses child_process) libraries should have a WritableStream available (source: https://nodejs.org/api/child_process.html#child_process_child_stdin ) at child.stdin.

I'm hoping to do something like this though I haven't had a chance to play with it yet:
```
var ftps_source = new lftp(config)
var source_stream = ftps.raw('get remote_file').execAsStream();

var ftps_destination = new lftp(config)
ftps.raw('put /dev/stdin -o remote_file.txt').exec();
source_stream.pipe( ftps_destination.stdin );
```

**Comment by dustinbolton** [comment]
@Atinux I figured out how to do this. The child_process instance returned by exec() and execAsStream() contains a stdin key which can be written to. lftp can take /dev/stdin as a data source.

```
var source_stream = ftps_source.raw('get wp-signup.php -o /dev/stdout').execAsStream();
var destination_stream = ftps_destination.raw('put /dev/stdin -o wp-signup.php').exec( console.log ).stdin;


```

**Comment by dustinbolton** [comment]
@Atinux I figured out how to do this:

```
var put_stream = ftps.raw('put /dev/stdin -o remote_file.txt').execAsStream();
```

You can then pipe into put_stream.
