### ISSUE TITLE
implementing your SSL solution in other plugin

### ISSUE THREAD

**Issue by 7vs** [Atinux/node-ftps#6]
Hi Atinux,
I come from the issue described in this link.
https://github.com/sergi/jsftp/issues/39
I'm trying to use this grunt plugin, but I need to add the SSL layer as the protocol needed to transfer to my ftp server is ftps.
How can I implement your solution in this plugin customised by myself?
thanks
rgds

**Comment by jwhitmarsh** [comment]
@7vs did you ever get anywhere with this?

**Comment by 7vs** [comment]
@ jwhitmarsh, No I didn't, why?
