### ISSUE TITLE
Error when trying to upload a file

### ISSUE THREAD

**Issue by thiagoperes** [Atinux/node-ftps#7]
Hi,

I'm trying to upload a file to a folder called 'test' which is on the root folder of the sftp server.

This is how I'm calling:
``
ftps.put(file.path, 'mobile/' + file.name).exec(console.log);
``

This is what I get:
``
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' } { error: null, data: '' }
``

I've also tried different path formats for the remote file, no sucess.

**Comment by agarwalarpit** [comment]
Any update on this? The entire package doesn't seem to be working for me.

**Comment by Atinux** [comment]
Hi, I'm not using this module anymore, but it's only a `lftp` wrapper, nothing more.
